title: Giwa Ibrahim
logo: "New Professional pics.jpg" # your photo (or logo) here
description: Junior Data Scientist with less than 1 year of Renewable Energy data experience and Ranked Top 5 in the recent Optimus AI Hackathon (April 2024)
show_downloads: true
theme: jekyll-theme-minimal
